# Generated by Django 2.2.5 on 2020-04-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntraGov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='name',
            field=models.CharField(default='defaultname', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='politician',
            name='house',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='politician',
            name='state_or_district',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
